name: Build using Cargo

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: rui314/setup-mold@v1
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.5.2
      - name: Build
        run: RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target x86_64-unknown-linux-gnu
      - run: mv target/x86_64-unknown-linux-gnu/release/piped-proxy piped-proxy
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: piped-proxy
          path: piped-proxy
