name: Run Tests

on:
    push:
        paths-ignore:
            - "**.md"
        branches:
            - main
    pull_request:
        paths-ignore:
            - "**.md"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: Swatinem/rust-cache@v2
            - uses: rui314/setup-mold@v1
            - name: Set up NASM
              uses: ilammy/setup-nasm@v1.5.2
            - name: Run tests
              run: cargo test
